//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teleboard.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teleboard.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email account confirmation sent. Please confirm before login.
        /// </summary>
        public static string AccountConfirmationEmailSent {
            get {
                return ResourceManager.GetString("AccountConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created. Please reset your password by clicking here: &lt;a href=&quot;{0}&quot;&gt;link&lt;/a&gt;&quot;.
        /// </summary>
        public static string AccountCreatedEmailBody {
            get {
                return ResourceManager.GetString("AccountCreatedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A New Device.
        /// </summary>
        public static string AddANewDevice {
            get {
                return ResourceManager.GetString("AddANewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A Phone Number.
        /// </summary>
        public static string AddAPhoneNumber {
            get {
                return ResourceManager.GetString("AddAPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Channel.
        /// </summary>
        public static string AddChannel {
            get {
                return ResourceManager.GetString("AddChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Content.
        /// </summary>
        public static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddDevice.
        /// </summary>
        public static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new channel.
        /// </summary>
        public static string AddNewChannel {
            get {
                return ResourceManager.GetString("AddNewChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Connection Type.
        /// </summary>
        public static string AddNewConnectionType {
            get {
                return ResourceManager.GetString("AddNewConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Content Type.
        /// </summary>
        public static string AddNewContentType {
            get {
                return ResourceManager.GetString("AddNewContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Role.
        /// </summary>
        public static string AddNewRole {
            get {
                return ResourceManager.GetString("AddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Tenant.
        /// </summary>
        public static string AddNewTenant {
            get {
                return ResourceManager.GetString("AddNewTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Translate.
        /// </summary>
        public static string AddNewTranslate {
            get {
                return ResourceManager.GetString("AddNewTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tenant.
        /// </summary>
        public static string AddTenant {
            get {
                return ResourceManager.GetString("AddTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements.
        /// </summary>
        public static string Advertisements {
            get {
                return ResourceManager.GetString("Advertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Contents.
        /// </summary>
        public static string AllContents {
            get {
                return ResourceManager.GetString("AllContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow advertisers to select this schedule.
        /// </summary>
        public static string AllowAdvertisementsInThisTimeBox {
            get {
                return ResourceManager.GetString("AllowAdvertisementsInThisTimeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed.
        /// </summary>
        public static string Allowed {
            get {
                return ResourceManager.GetString("Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleboard.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Content.
        /// </summary>
        public static string ApproveContent {
            get {
                return ResourceManager.GetString("ApproveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Approve this?.
        /// </summary>
        public static string AreYouSureYouWantToApproveThis {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToApproveThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your {0} account.
        /// </summary>
        public static string AssociateYourLoginProviderAccount {
            get {
                return ResourceManager.GetString("AssociateYourLoginProviderAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string AssociationForm {
            get {
                return ResourceManager.GetString("AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add role(s) to the user.
        /// </summary>
        public static string CannotAddRolesToUser {
            get {
                return ResourceManager.GetString("CannotAddRolesToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add tenant(s) to the user.
        /// </summary>
        public static string CannotAddTenantsToUser {
            get {
                return ResourceManager.GetString("CannotAddTenantsToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string ChangeYourAccountSettings {
            get {
                return ResourceManager.GetString("ChangeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Contents.
        /// </summary>
        public static string ChannelContents {
            get {
                return ResourceManager.GetString("ChannelContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Details.
        /// </summary>
        public static string ChannelDetails {
            get {
                return ResourceManager.GetString("ChannelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email (and your spam box) to reset your password.
        /// </summary>
        public static string CheckYourEmailToResetPassword {
            get {
                return ResourceManager.GetString("CheckYourEmailToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        public static string ConfirmAccountEmailBody {
            get {
                return ResourceManager.GetString("ConfirmAccountEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Account.
        /// </summary>
        public static string ConfirmYourAccount {
            get {
                return ResourceManager.GetString("ConfirmYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionType.
        /// </summary>
        public static string ConnectionType {
            get {
                return ResourceManager.GetString("ConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Types.
        /// </summary>
        public static string ConnectionTypes {
            get {
                return ResourceManager.GetString("ConnectionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playing ads for your tenant is disabled..
        /// </summary>
        public static string ContactAdminToEnableAdsForYourTenant {
            get {
                return ResourceManager.GetString("ContactAdminToEnableAdsForYourTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Approval.
        /// </summary>
        public static string ContentApproval {
            get {
                return ResourceManager.GetString("ContentApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totall play duration of selected advertisements exceeded this schedule duration. please deselect some advertisements or reduce their play times..
        /// </summary>
        public static string ContentsDurationExceededTimeBoxDuration {
            get {
                return ResourceManager.GetString("ContentsDurationExceededTimeBoxDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents Of Channel.
        /// </summary>
        public static string ContentsOfChannel {
            get {
                return ResourceManager.GetString("ContentsOfChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type Not Defined.
        /// </summary>
        public static string ContentTypeNotDefined {
            get {
                return ResourceManager.GetString("ContentTypeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Types.
        /// </summary>
        public static string ContentTypes {
            get {
                return ResourceManager.GetString("ContentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Local Login.
        /// </summary>
        public static string CreateLocalLogin {
            get {
                return ResourceManager.GetString("CreateLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create A New Account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day View.
        /// </summary>
        public static string DayView {
            get {
                return ResourceManager.GetString("DayView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Channel.
        /// </summary>
        public static string DeleteChannel {
            get {
                return ResourceManager.GetString("DeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete This Channel.
        /// </summary>
        public static string DeleteThisChannel {
            get {
                return ResourceManager.GetString("DeleteThisChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete This Device.
        /// </summary>
        public static string DeleteThisDevice {
            get {
                return ResourceManager.GetString("DeleteThisDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Details.
        /// </summary>
        public static string DeviceDetails {
            get {
                return ResourceManager.GetString("DeviceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id.
        /// </summary>
        public static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device identifier is used for another device, please use a diffrent device identifier..
        /// </summary>
        public static string DeviceIdentifierIsDuplicate {
            get {
                return ResourceManager.GetString("DeviceIdentifierIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Time Box.
        /// </summary>
        public static string DeviceTimeBox {
            get {
                return ResourceManager.GetString("DeviceTimeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string DidYouForgetYourPassword {
            get {
                return ResourceManager.GetString("DidYouForgetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know?.
        /// </summary>
        public static string DidYouKnow {
            get {
                return ResourceManager.GetString("DidYouKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A channel with this name  exist, please enter a diffrent name.
        /// </summary>
        public static string DuplicateChannelName {
            get {
                return ResourceManager.GetString("DuplicateChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Channel.
        /// </summary>
        public static string EditChannel {
            get {
                return ResourceManager.GetString("EditChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Content.
        /// </summary>
        public static string EditContent {
            get {
                return ResourceManager.GetString("EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device.
        /// </summary>
        public static string EditDevice {
            get {
                return ResourceManager.GetString("EditDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create confirmation email.
        /// </summary>
        public static string EmailConfirmationFailed {
            get {
                return ResourceManager.GetString("EmailConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Reset Link.
        /// </summary>
        public static string EmailResetLink {
            get {
                return ResourceManager.GetString("EmailResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Verification Code.
        /// </summary>
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See &lt;a href=&quot;http://go.microsoft.com/fwlink/?LinkId=313242&quot;&gt;this article&lt;/a&gt;
        ///                for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string ExternalAuthenticationConfigurationMessage {
            get {
                return ResourceManager.GetString("ExternalAuthenticationConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed.
        /// </summary>
        public static string ExternalLoginRemoved {
            get {
                return ResourceManager.GetString("ExternalLoginRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins.
        /// </summary>
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi.
        /// </summary>
        public static string Farsi {
            get {
                return ResourceManager.GetString("Farsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string FileSizeInMegaBytes {
            get {
                return ResourceManager.GetString("FileSizeInMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Time.
        /// </summary>
        public static string FreeTime {
            get {
                return ResourceManager.GetString("FreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Scheduling.
        /// </summary>
        public static string GroupScheduling {
            get {
                return ResourceManager.GetString("GroupScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date Range.
        /// </summary>
        public static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an invalid email. please enter your account email..
        /// </summary>
        public static string InvalidEmailForResetPassword {
            get {
                return ResourceManager.GetString("InvalidEmailForResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reset password link.
        /// </summary>
        public static string InvalidResetPasswordParameter {
            get {
                return ResourceManager.GetString("InvalidResetPasswordParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidSubscriptionCode.
        /// </summary>
        public static string InvalidSubscriptionCode {
            get {
                return ResourceManager.GetString("InvalidSubscriptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Connectivity.
        /// </summary>
        public static string LastConnectivity {
            get {
                return ResourceManager.GetString("LastConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Device Scheduling.
        /// </summary>
        public static string LoadDeviceScheduling {
            get {
                return ResourceManager.GetString("LoadDeviceScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account.
        /// </summary>
        public static string LoginUsingYourProvider {
            get {
                return ResourceManager.GetString("LoginUsingYourProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string ManageYourExternalLogins {
            get {
                return ResourceManager.GetString("ManageYourExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing parameter.
        /// </summary>
        public static string MissingParameter {
            get {
                return ResourceManager.GetString("MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderation On Chennal.
        /// </summary>
        public static string ModerationOnChennal {
            get {
                return ResourceManager.GetString("ModerationOnChennal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderation On Content.
        /// </summary>
        public static string ModerationOnContent {
            get {
                return ResourceManager.GetString("ModerationOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderation On TimeBox.
        /// </summary>
        public static string ModerationOnTimeBox {
            get {
                return ResourceManager.GetString("ModerationOnTimeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length of field {0} must be between {1} and {2}.
        /// </summary>
        public static string MsgStringLengthRange {
            get {
                return ResourceManager.GetString("MsgStringLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewValue.
        /// </summary>
        public static string NewKey {
            get {
                return ResourceManager.GetString("NewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contents.
        /// </summary>
        public static string NoContents {
            get {
                return ResourceManager.GetString("NoContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contents to approve.
        /// </summary>
        public static string NoContentsToApprove {
            get {
                return ResourceManager.GetString("NoContentsToApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotAllowed.
        /// </summary>
        public static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not approved.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no two-factor authentication providers configured. See &lt;a href=&quot;http://go.microsoft.com/fwlink/?LinkId=403804&quot;&gt;this article&lt;/a&gt;
        ///                for details on setting up this ASP.NET application to support two-factor authentication..
        /// </summary>
        public static string NoTwoFactorAuthenticationProvidersConfigured {
            get {
                return ResourceManager.GetString("NoTwoFactorAuthenticationProvidersConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the device that you want your advertisements play on it..
        /// </summary>
        public static string PageHelpMessage_AdsDevices_Index {
            get {
                return ResourceManager.GetString("PageHelpMessage_AdsDevices_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an enabled schedule and then choose advertisements to play on this device..
        /// </summary>
        public static string PageHelpMessage_AdsTimeBox_Index {
            get {
                return ResourceManager.GetString("PageHelpMessage_AdsTimeBox_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this page you can view contents that are pending to approve. these contents won&apos;t be played in devices until you approve them!.
        /// </summary>
        public static string PageHelpMessage_Approval_Index {
            get {
                return ResourceManager.GetString("PageHelpMessage_Approval_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this page you can manage channel contents. all contents of your tenant are shown in the left column.  to add a content to the channel, click &apos;Move&apos; button. after clicking &apos;Move&apos; button, it will be added to contents of this channel..
        /// </summary>
        public static string PageHelpMessage_Channel_Contents {
            get {
                return ResourceManager.GetString("PageHelpMessage_Channel_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this page you can view your channels. to add contents to each channel, click &apos;Channel Contents&apos; icon..
        /// </summary>
        public static string PageHelpMessage_Channel_Index {
            get {
                return ResourceManager.GetString("PageHelpMessage_Channel_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this page you can view your contents and approve them if you are administrator..
        /// </summary>
        public static string PageHelpMessage_Content_Index {
            get {
                return ResourceManager.GetString("PageHelpMessage_Content_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, in this page you can see your uploaded advertisments. to add a new advertisment, click &apos;Add Content&apos; button. please notice that your advertisments will play on devices only after approval..
        /// </summary>
        public static string PageHelpMessage_Content_Index_ForAdvertiser {
            get {
                return ResourceManager.GetString("PageHelpMessage_Content_Index_ForAdvertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this page you can view your devices and schedule them..
        /// </summary>
        public static string PageHelpMessage_Schedule_Index {
            get {
                return ResourceManager.GetString("PageHelpMessage_Schedule_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this page you can add a device. please select device time zone based on your geographical location. contents will be played on this device based on local time of the device.&lt;br/&gt;
        ///enter &apos;DeviceId&apos; that you have gotten from your device app..
        /// </summary>
        public static string PageHelpMessage_Scheduler_Create {
            get {
                return ResourceManager.GetString("PageHelpMessage_Scheduler_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this page you can schdule your device. select a date range for playing a channel. after selecting a date range, in the opened window select the channel that you want play in that period of time..
        /// </summary>
        public static string PageHelpMessage_TimeBox_Index {
            get {
                return ResourceManager.GetString("PageHelpMessage_TimeBox_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Ads.
        /// </summary>
        public static string PlayAdvertisement {
            get {
                return ResourceManager.GetString("PlayAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing ads for this tenant is disabled.
        /// </summary>
        public static string PlayingAdsForThisTenantIsDisabled {
            get {
                return ResourceManager.GetString("PlayingAdsForThisTenantIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login Teleboard And Approve Contents which are pending for approval. Thank You!.
        /// </summary>
        public static string PleaseApproveContents {
            get {
                return ResourceManager.GetString("PleaseApproveContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a channel first..
        /// </summary>
        public static string PleaseCreateAChannel {
            get {
                return ResourceManager.GetString("PleaseCreateAChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Date.
        /// </summary>
        public static string RegisterationDate {
            get {
                return ResourceManager.GetString("RegisterationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string RegisteredLogins {
            get {
                return ResourceManager.GetString("RegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Schedulings.
        /// </summary>
        public static string RemoveAllSchedulings {
            get {
                return ResourceManager.GetString("RemoveAllSchedulings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Confirmation.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking here: &lt;a href=&quot;{0}&quot;&gt;Reset Password&lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordEmailBody {
            get {
                return ResourceManager.GetString("ResetPasswordEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password To Default.
        /// </summary>
        public static string ResetPasswordToDefault {
            get {
                return ResourceManager.GetString("ResetPasswordToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        public static string ResetYourPassword {
            get {
                return ResourceManager.GetString("ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Group Scheduling.
        /// </summary>
        public static string SaveGroupScheduling {
            get {
                return ResourceManager.GetString("SaveGroupScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this time box.
        /// </summary>
        public static string SaveThisTimeBox {
            get {
                return ResourceManager.GetString("SaveThisTimeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Device.
        /// </summary>
        public static string ScheduleDevice {
            get {
                return ResourceManager.GetString("ScheduleDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec.
        /// </summary>
        public static string Sec {
            get {
                return ResourceManager.GetString("Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected contents for displaying in channel.
        /// </summary>
        public static string SelectedContentsForDisplayingInChannel {
            get {
                return ResourceManager.GetString("SelectedContentsForDisplayingInChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Task For List Bellow.
        /// </summary>
        public static string SelectTaskForListBellow {
            get {
                return ResourceManager.GetString("SelectTaskForListBellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider.
        /// </summary>
        public static string SelectTwoFactorAuthenticationProvider {
            get {
                return ResourceManager.GetString("SelectTwoFactorAuthenticationProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Verification Code.
        /// </summary>
        public static string SendVerificationCode {
            get {
                return ResourceManager.GetString("SendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your account.
        /// </summary>
        public static string SignInToYourAccount {
            get {
                return ResourceManager.GetString("SignInToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Types.
        /// </summary>
        public static string SupportedMimeTypes {
            get {
                return ResourceManager.GetString("SupportedMimeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only this type of files are supported. if you want upload a file that it&apos;s type is not appeared in this list, please contact your system administrator and ask him/her to add the file MIME type..
        /// </summary>
        public static string SupportedMimeTypesMessage {
            get {
                return ResourceManager.GetString("SupportedMimeTypesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanant Name.
        /// </summary>
        public static string TanantName {
            get {
                return ResourceManager.GetString("TanantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements.
        /// </summary>
        public static string TenantAdvertisementStatus {
            get {
                return ResourceManager.GetString("TenantAdvertisementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string TenantName {
            get {
                return ResourceManager.GetString("TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string Tenants {
            get {
                return ResourceManager.GetString("Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email, Please &lt;a id=&quot;loginLink&quot; href=&quot;/Account/Login&quot;&gt; Click here to Log in&lt;/a&gt;.
        /// </summary>
        public static string ThankYouForConfirmingEmailMessage {
            get {
                return ResourceManager.GetString("ThankYouForConfirmingEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See &lt;a href=&quot;http://go.microsoft.com/fwlink/?LinkId=403804&quot;&gt;this article&lt;/a&gt;
        ///                for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string ThereAreNoExternalAuthenticationServicesConfigured {
            get {
                return ResourceManager.GetString("ThereAreNoExternalAuthenticationServicesConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Box.
        /// </summary>
        public static string TimeBox {
            get {
                return ResourceManager.GetString("TimeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Boxes.
        /// </summary>
        public static string TimeBoxes {
            get {
                return ResourceManager.GetString("TimeBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Authentication.
        /// </summary>
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your two-factor authentication provider has been set..
        /// </summary>
        public static string TwoFactorAuthenticationHasBeenSet {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service.
        /// </summary>
        public static string UnsuccessfulLoginWithService {
            get {
                return ResourceManager.GetString("UnsuccessfulLoginWithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in.
        /// </summary>
        public static string UseAnotherServiceToLogIn {
            get {
                return ResourceManager.GetString("UseAnotherServiceToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email Is Not Confirmed.
        /// </summary>
        public static string UserEmailIsNotConfirmed {
            get {
                return ResourceManager.GetString("UserEmailIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found or email has not been confirmed.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string VerifyPhoneNumber {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Seconds.
        /// </summary>
        public static string WaitSeconds {
            get {
                return ResourceManager.GetString("WaitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week View.
        /// </summary>
        public static string WeekView {
            get {
                return ResourceManager.GetString("WeekView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local
        /// account so you can log in without an external login..
        /// </summary>
        public static string YouHaveNotLocalAccountMessage {
            get {
                return ResourceManager.GetString("YouHaveNotLocalAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a confirmed email to log in..
        /// </summary>
        public static string YouNeedConfirmedEmailToLogin {
            get {
                return ResourceManager.GetString("YouNeedConfirmedEmailToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser does not support the video tag..
        /// </summary>
        public static string YourBrowserDoesNotSupportVideoTag {
            get {
                return ResourceManager.GetString("YourBrowserDoesNotSupportVideoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        public static string YourPasswordChanged {
            get {
                return ResourceManager.GetString("YourPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set.
        /// </summary>
        public static string YourPasswordHasBeenSet {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        ///        Please &lt;a id = &quot;loginLink&quot; href=&quot;/Account/Login&quot;&gt;click here to log in&lt;/a&gt;.
        /// </summary>
        public static string YourPasswordHasResetMessage {
            get {
                return ResourceManager.GetString("YourPasswordHasResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was added.
        /// </summary>
        public static string YourPhoneNumberAdded {
            get {
                return ResourceManager.GetString("YourPhoneNumberAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was removed.
        /// </summary>
        public static string YourPhoneNumberRemoved {
            get {
                return ResourceManager.GetString("YourPhoneNumberRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code is: .
        /// </summary>
        public static string YourSecurityCode {
            get {
                return ResourceManager.GetString("YourSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with &lt;strong&gt;{0}&lt;/strong&gt;.
        ///        Please enter a user name for this site below and click the Register button to finish
        ///        logging in..
        /// </summary>
        public static string YouSuccessfullyAuthenticatedWithProvider {
            get {
                return ResourceManager.GetString("YouSuccessfullyAuthenticatedWithProvider", resourceCulture);
            }
        }
    }
}
